/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// AddUsersDto
    /// </summary>
    [DataContract(Name = "AddUsersDto")]
    public partial class AddUsersDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddUsersDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddUsersDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddUsersDto" /> class.
        /// </summary>
        /// <param name="albumUsers">albumUsers (required).</param>
        public AddUsersDto(List<AlbumUserAddDto> albumUsers = default(List<AlbumUserAddDto>))
        {
            // to ensure "albumUsers" is required (not null)
            if (albumUsers == null)
            {
                throw new ArgumentNullException("albumUsers is a required property for AddUsersDto and cannot be null");
            }
            this.AlbumUsers = albumUsers;
        }

        /// <summary>
        /// Gets or Sets AlbumUsers
        /// </summary>
        [DataMember(Name = "albumUsers", IsRequired = true, EmitDefaultValue = true)]
        public List<AlbumUserAddDto> AlbumUsers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddUsersDto {\n");
            sb.Append("  AlbumUsers: ").Append(AlbumUsers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
