/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// Defines AlbumUserRole
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AlbumUserRole
    {
        /// <summary>
        /// Enum Editor for value: editor
        /// </summary>
        [EnumMember(Value = "editor")]
        Editor = 1,

        /// <summary>
        /// Enum Viewer for value: viewer
        /// </summary>
        [EnumMember(Value = "viewer")]
        Viewer = 2
    }

}
