/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// AssetFullSyncDto
    /// </summary>
    [DataContract(Name = "AssetFullSyncDto")]
    public partial class AssetFullSyncDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetFullSyncDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AssetFullSyncDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetFullSyncDto" /> class.
        /// </summary>
        /// <param name="lastId">lastId.</param>
        /// <param name="limit">limit (required).</param>
        /// <param name="updatedUntil">updatedUntil (required).</param>
        /// <param name="userId">userId.</param>
        public AssetFullSyncDto(Guid lastId = default(Guid), int limit = default(int), DateTime updatedUntil = default(DateTime), Guid userId = default(Guid))
        {
            this.Limit = limit;
            this.UpdatedUntil = updatedUntil;
            this.LastId = lastId;
            this.UserId = userId;
        }

        /// <summary>
        /// Gets or Sets LastId
        /// </summary>
        [DataMember(Name = "lastId", EmitDefaultValue = false)]
        public Guid LastId { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public int Limit { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedUntil
        /// </summary>
        [DataMember(Name = "updatedUntil", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedUntil { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public Guid UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssetFullSyncDto {\n");
            sb.Append("  LastId: ").Append(LastId).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  UpdatedUntil: ").Append(UpdatedUntil).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Limit (int) minimum
            if (this.Limit < (int)1)
            {
                yield return new ValidationResult("Invalid value for Limit, must be a value greater than or equal to 1.", new [] { "Limit" });
            }

            yield break;
        }
    }

}
