/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// AssetBulkUpdateDto
    /// </summary>
    [DataContract(Name = "AssetBulkUpdateDto")]
    public partial class AssetBulkUpdateDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetBulkUpdateDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AssetBulkUpdateDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetBulkUpdateDto" /> class.
        /// </summary>
        /// <param name="dateTimeOriginal">dateTimeOriginal.</param>
        /// <param name="duplicateId">duplicateId.</param>
        /// <param name="ids">ids (required).</param>
        /// <param name="isArchived">isArchived.</param>
        /// <param name="isFavorite">isFavorite.</param>
        /// <param name="latitude">latitude.</param>
        /// <param name="longitude">longitude.</param>
        /// <param name="removeParent">removeParent.</param>
        /// <param name="stackParentId">stackParentId.</param>
        public AssetBulkUpdateDto(string dateTimeOriginal = default(string), string duplicateId = default(string), List<Guid> ids = default(List<Guid>), bool isArchived = default(bool), bool isFavorite = default(bool), decimal latitude = default(decimal), decimal longitude = default(decimal), bool removeParent = default(bool), Guid stackParentId = default(Guid))
        {
            // to ensure "ids" is required (not null)
            if (ids == null)
            {
                throw new ArgumentNullException("ids is a required property for AssetBulkUpdateDto and cannot be null");
            }
            this.Ids = ids;
            this.DateTimeOriginal = dateTimeOriginal;
            this.DuplicateId = duplicateId;
            this.IsArchived = isArchived;
            this.IsFavorite = isFavorite;
            this.Latitude = latitude;
            this.Longitude = longitude;
            this.RemoveParent = removeParent;
            this.StackParentId = stackParentId;
        }

        /// <summary>
        /// Gets or Sets DateTimeOriginal
        /// </summary>
        [DataMember(Name = "dateTimeOriginal", EmitDefaultValue = false)]
        public string DateTimeOriginal { get; set; }

        /// <summary>
        /// Gets or Sets DuplicateId
        /// </summary>
        [DataMember(Name = "duplicateId", EmitDefaultValue = true)]
        public string DuplicateId { get; set; }

        /// <summary>
        /// Gets or Sets Ids
        /// </summary>
        [DataMember(Name = "ids", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> Ids { get; set; }

        /// <summary>
        /// Gets or Sets IsArchived
        /// </summary>
        [DataMember(Name = "isArchived", EmitDefaultValue = true)]
        public bool IsArchived { get; set; }

        /// <summary>
        /// Gets or Sets IsFavorite
        /// </summary>
        [DataMember(Name = "isFavorite", EmitDefaultValue = true)]
        public bool IsFavorite { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name = "latitude", EmitDefaultValue = false)]
        public decimal Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [DataMember(Name = "longitude", EmitDefaultValue = false)]
        public decimal Longitude { get; set; }

        /// <summary>
        /// Gets or Sets RemoveParent
        /// </summary>
        [DataMember(Name = "removeParent", EmitDefaultValue = true)]
        public bool RemoveParent { get; set; }

        /// <summary>
        /// Gets or Sets StackParentId
        /// </summary>
        [DataMember(Name = "stackParentId", EmitDefaultValue = false)]
        public Guid StackParentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssetBulkUpdateDto {\n");
            sb.Append("  DateTimeOriginal: ").Append(DateTimeOriginal).Append("\n");
            sb.Append("  DuplicateId: ").Append(DuplicateId).Append("\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("  IsArchived: ").Append(IsArchived).Append("\n");
            sb.Append("  IsFavorite: ").Append(IsFavorite).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  RemoveParent: ").Append(RemoveParent).Append("\n");
            sb.Append("  StackParentId: ").Append(StackParentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
