/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// Defines AssetJobName
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AssetJobName
    {
        /// <summary>
        /// Enum RegenerateThumbnail for value: regenerate-thumbnail
        /// </summary>
        [EnumMember(Value = "regenerate-thumbnail")]
        RegenerateThumbnail = 1,

        /// <summary>
        /// Enum RefreshMetadata for value: refresh-metadata
        /// </summary>
        [EnumMember(Value = "refresh-metadata")]
        RefreshMetadata = 2,

        /// <summary>
        /// Enum TranscodeVideo for value: transcode-video
        /// </summary>
        [EnumMember(Value = "transcode-video")]
        TranscodeVideo = 3
    }

}
