/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// Defines AssetTypeEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AssetTypeEnum
    {
        /// <summary>
        /// Enum IMAGE for value: IMAGE
        /// </summary>
        [EnumMember(Value = "IMAGE")]
        IMAGE = 1,

        /// <summary>
        /// Enum VIDEO for value: VIDEO
        /// </summary>
        [EnumMember(Value = "VIDEO")]
        VIDEO = 2,

        /// <summary>
        /// Enum AUDIO for value: AUDIO
        /// </summary>
        [EnumMember(Value = "AUDIO")]
        AUDIO = 3,

        /// <summary>
        /// Enum OTHER for value: OTHER
        /// </summary>
        [EnumMember(Value = "OTHER")]
        OTHER = 4
    }

}
