/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// FileReportDto
    /// </summary>
    [DataContract(Name = "FileReportDto")]
    public partial class FileReportDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileReportDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FileReportDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FileReportDto" /> class.
        /// </summary>
        /// <param name="extras">extras (required).</param>
        /// <param name="orphans">orphans (required).</param>
        public FileReportDto(List<string> extras = default(List<string>), List<FileReportItemDto> orphans = default(List<FileReportItemDto>))
        {
            // to ensure "extras" is required (not null)
            if (extras == null)
            {
                throw new ArgumentNullException("extras is a required property for FileReportDto and cannot be null");
            }
            this.Extras = extras;
            // to ensure "orphans" is required (not null)
            if (orphans == null)
            {
                throw new ArgumentNullException("orphans is a required property for FileReportDto and cannot be null");
            }
            this.Orphans = orphans;
        }

        /// <summary>
        /// Gets or Sets Extras
        /// </summary>
        [DataMember(Name = "extras", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Extras { get; set; }

        /// <summary>
        /// Gets or Sets Orphans
        /// </summary>
        [DataMember(Name = "orphans", IsRequired = true, EmitDefaultValue = true)]
        public List<FileReportItemDto> Orphans { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FileReportDto {\n");
            sb.Append("  Extras: ").Append(Extras).Append("\n");
            sb.Append("  Orphans: ").Append(Orphans).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
