/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// Defines JobName
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum JobName
    {
        /// <summary>
        /// Enum ThumbnailGeneration for value: thumbnailGeneration
        /// </summary>
        [EnumMember(Value = "thumbnailGeneration")]
        ThumbnailGeneration = 1,

        /// <summary>
        /// Enum MetadataExtraction for value: metadataExtraction
        /// </summary>
        [EnumMember(Value = "metadataExtraction")]
        MetadataExtraction = 2,

        /// <summary>
        /// Enum VideoConversion for value: videoConversion
        /// </summary>
        [EnumMember(Value = "videoConversion")]
        VideoConversion = 3,

        /// <summary>
        /// Enum FaceDetection for value: faceDetection
        /// </summary>
        [EnumMember(Value = "faceDetection")]
        FaceDetection = 4,

        /// <summary>
        /// Enum FacialRecognition for value: facialRecognition
        /// </summary>
        [EnumMember(Value = "facialRecognition")]
        FacialRecognition = 5,

        /// <summary>
        /// Enum SmartSearch for value: smartSearch
        /// </summary>
        [EnumMember(Value = "smartSearch")]
        SmartSearch = 6,

        /// <summary>
        /// Enum DuplicateDetection for value: duplicateDetection
        /// </summary>
        [EnumMember(Value = "duplicateDetection")]
        DuplicateDetection = 7,

        /// <summary>
        /// Enum BackgroundTask for value: backgroundTask
        /// </summary>
        [EnumMember(Value = "backgroundTask")]
        BackgroundTask = 8,

        /// <summary>
        /// Enum StorageTemplateMigration for value: storageTemplateMigration
        /// </summary>
        [EnumMember(Value = "storageTemplateMigration")]
        StorageTemplateMigration = 9,

        /// <summary>
        /// Enum Migration for value: migration
        /// </summary>
        [EnumMember(Value = "migration")]
        Migration = 10,

        /// <summary>
        /// Enum Search for value: search
        /// </summary>
        [EnumMember(Value = "search")]
        Search = 11,

        /// <summary>
        /// Enum Sidecar for value: sidecar
        /// </summary>
        [EnumMember(Value = "sidecar")]
        Sidecar = 12,

        /// <summary>
        /// Enum Library for value: library
        /// </summary>
        [EnumMember(Value = "library")]
        Library = 13,

        /// <summary>
        /// Enum Notifications for value: notifications
        /// </summary>
        [EnumMember(Value = "notifications")]
        Notifications = 14
    }

}
