/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// SystemConfigServerDto
    /// </summary>
    [DataContract(Name = "SystemConfigServerDto")]
    public partial class SystemConfigServerDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigServerDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SystemConfigServerDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigServerDto" /> class.
        /// </summary>
        /// <param name="externalDomain">externalDomain (required).</param>
        /// <param name="loginPageMessage">loginPageMessage (required).</param>
        public SystemConfigServerDto(string externalDomain = default(string), string loginPageMessage = default(string))
        {
            // to ensure "externalDomain" is required (not null)
            if (externalDomain == null)
            {
                throw new ArgumentNullException("externalDomain is a required property for SystemConfigServerDto and cannot be null");
            }
            this.ExternalDomain = externalDomain;
            // to ensure "loginPageMessage" is required (not null)
            if (loginPageMessage == null)
            {
                throw new ArgumentNullException("loginPageMessage is a required property for SystemConfigServerDto and cannot be null");
            }
            this.LoginPageMessage = loginPageMessage;
        }

        /// <summary>
        /// Gets or Sets ExternalDomain
        /// </summary>
        [DataMember(Name = "externalDomain", IsRequired = true, EmitDefaultValue = true)]
        public string ExternalDomain { get; set; }

        /// <summary>
        /// Gets or Sets LoginPageMessage
        /// </summary>
        [DataMember(Name = "loginPageMessage", IsRequired = true, EmitDefaultValue = true)]
        public string LoginPageMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SystemConfigServerDto {\n");
            sb.Append("  ExternalDomain: ").Append(ExternalDomain).Append("\n");
            sb.Append("  LoginPageMessage: ").Append(LoginPageMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
