/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// SystemConfigTrashDto
    /// </summary>
    [DataContract(Name = "SystemConfigTrashDto")]
    public partial class SystemConfigTrashDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigTrashDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SystemConfigTrashDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigTrashDto" /> class.
        /// </summary>
        /// <param name="days">days (required).</param>
        /// <param name="enabled">enabled (required).</param>
        public SystemConfigTrashDto(int days = default(int), bool enabled = default(bool))
        {
            this.Days = days;
            this.Enabled = enabled;
        }

        /// <summary>
        /// Gets or Sets Days
        /// </summary>
        [DataMember(Name = "days", IsRequired = true, EmitDefaultValue = true)]
        public int Days { get; set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SystemConfigTrashDto {\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Days (int) minimum
            if (this.Days < (int)0)
            {
                yield return new ValidationResult("Invalid value for Days, must be a value greater than or equal to 0.", new [] { "Days" });
            }

            yield break;
        }
    }

}
