/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// SystemConfigNotificationsDto
    /// </summary>
    [DataContract(Name = "SystemConfigNotificationsDto")]
    public partial class SystemConfigNotificationsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigNotificationsDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SystemConfigNotificationsDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigNotificationsDto" /> class.
        /// </summary>
        /// <param name="smtp">smtp (required).</param>
        public SystemConfigNotificationsDto(SystemConfigSmtpDto smtp = default(SystemConfigSmtpDto))
        {
            // to ensure "smtp" is required (not null)
            if (smtp == null)
            {
                throw new ArgumentNullException("smtp is a required property for SystemConfigNotificationsDto and cannot be null");
            }
            this.Smtp = smtp;
        }

        /// <summary>
        /// Gets or Sets Smtp
        /// </summary>
        [DataMember(Name = "smtp", IsRequired = true, EmitDefaultValue = true)]
        public SystemConfigSmtpDto Smtp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SystemConfigNotificationsDto {\n");
            sb.Append("  Smtp: ").Append(Smtp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
