/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// Defines ToneMapping
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ToneMapping
    {
        /// <summary>
        /// Enum Hable for value: hable
        /// </summary>
        [EnumMember(Value = "hable")]
        Hable = 1,

        /// <summary>
        /// Enum Mobius for value: mobius
        /// </summary>
        [EnumMember(Value = "mobius")]
        Mobius = 2,

        /// <summary>
        /// Enum Reinhard for value: reinhard
        /// </summary>
        [EnumMember(Value = "reinhard")]
        Reinhard = 3,

        /// <summary>
        /// Enum Disabled for value: disabled
        /// </summary>
        [EnumMember(Value = "disabled")]
        Disabled = 4
    }

}
