/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// Defines TranscodePolicy
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TranscodePolicy
    {
        /// <summary>
        /// Enum All for value: all
        /// </summary>
        [EnumMember(Value = "all")]
        All = 1,

        /// <summary>
        /// Enum Optimal for value: optimal
        /// </summary>
        [EnumMember(Value = "optimal")]
        Optimal = 2,

        /// <summary>
        /// Enum Bitrate for value: bitrate
        /// </summary>
        [EnumMember(Value = "bitrate")]
        Bitrate = 3,

        /// <summary>
        /// Enum Required for value: required
        /// </summary>
        [EnumMember(Value = "required")]
        Required = 4,

        /// <summary>
        /// Enum Disabled for value: disabled
        /// </summary>
        [EnumMember(Value = "disabled")]
        Disabled = 5
    }

}
