/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// UpdatePartnerDto
    /// </summary>
    [DataContract(Name = "UpdatePartnerDto")]
    public partial class UpdatePartnerDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePartnerDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdatePartnerDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePartnerDto" /> class.
        /// </summary>
        /// <param name="inTimeline">inTimeline (required).</param>
        public UpdatePartnerDto(bool inTimeline = default(bool))
        {
            this.InTimeline = inTimeline;
        }

        /// <summary>
        /// Gets or Sets InTimeline
        /// </summary>
        [DataMember(Name = "inTimeline", IsRequired = true, EmitDefaultValue = true)]
        public bool InTimeline { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdatePartnerDto {\n");
            sb.Append("  InTimeline: ").Append(InTimeline).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
