/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// UserLicense
    /// </summary>
    [DataContract(Name = "UserLicense")]
    public partial class UserLicense : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserLicense" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserLicense() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserLicense" /> class.
        /// </summary>
        /// <param name="activatedAt">activatedAt (required).</param>
        /// <param name="activationKey">activationKey (required).</param>
        /// <param name="licenseKey">licenseKey (required).</param>
        public UserLicense(DateTime activatedAt = default(DateTime), string activationKey = default(string), string licenseKey = default(string))
        {
            this.ActivatedAt = activatedAt;
            // to ensure "activationKey" is required (not null)
            if (activationKey == null)
            {
                throw new ArgumentNullException("activationKey is a required property for UserLicense and cannot be null");
            }
            this.ActivationKey = activationKey;
            // to ensure "licenseKey" is required (not null)
            if (licenseKey == null)
            {
                throw new ArgumentNullException("licenseKey is a required property for UserLicense and cannot be null");
            }
            this.LicenseKey = licenseKey;
        }

        /// <summary>
        /// Gets or Sets ActivatedAt
        /// </summary>
        [DataMember(Name = "activatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ActivatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ActivationKey
        /// </summary>
        [DataMember(Name = "activationKey", IsRequired = true, EmitDefaultValue = true)]
        public string ActivationKey { get; set; }

        /// <summary>
        /// Gets or Sets LicenseKey
        /// </summary>
        [DataMember(Name = "licenseKey", IsRequired = true, EmitDefaultValue = true)]
        public string LicenseKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserLicense {\n");
            sb.Append("  ActivatedAt: ").Append(ActivatedAt).Append("\n");
            sb.Append("  ActivationKey: ").Append(ActivationKey).Append("\n");
            sb.Append("  LicenseKey: ").Append(LicenseKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
