/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ImmichApi.Client.OpenAPIDateConverter;

namespace ImmichApi.Model
{
    /// <summary>
    /// ValidateLibraryDto
    /// </summary>
    [DataContract(Name = "ValidateLibraryDto")]
    public partial class ValidateLibraryDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateLibraryDto" /> class.
        /// </summary>
        /// <param name="exclusionPatterns">exclusionPatterns.</param>
        /// <param name="importPaths">importPaths.</param>
        public ValidateLibraryDto(List<string> exclusionPatterns = default(List<string>), List<string> importPaths = default(List<string>))
        {
            this.ExclusionPatterns = exclusionPatterns;
            this.ImportPaths = importPaths;
        }

        /// <summary>
        /// Gets or Sets ExclusionPatterns
        /// </summary>
        [DataMember(Name = "exclusionPatterns", EmitDefaultValue = false)]
        public List<string> ExclusionPatterns { get; set; }

        /// <summary>
        /// Gets or Sets ImportPaths
        /// </summary>
        [DataMember(Name = "importPaths", EmitDefaultValue = false)]
        public List<string> ImportPaths { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidateLibraryDto {\n");
            sb.Append("  ExclusionPatterns: ").Append(ExclusionPatterns).Append("\n");
            sb.Append("  ImportPaths: ").Append(ImportPaths).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
