/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ImmichApi.Client;
using ImmichApi.Api;
// uncomment below to import models
//using ImmichApi.Model;

namespace ImmichApi.Test.Api
{
    /// <summary>
    ///  Class for testing TimelineApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TimelineApiTests : IDisposable
    {
        private TimelineApi instance;

        public TimelineApiTests()
        {
            instance = new TimelineApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimelineApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TimelineApi
            //Assert.IsType<TimelineApi>(instance);
        }

        /// <summary>
        /// Test GetTimeBucket
        /// </summary>
        [Fact]
        public void GetTimeBucketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TimeBucketSize size = null;
            //string timeBucket = null;
            //Guid? albumId = null;
            //bool? isArchived = null;
            //bool? isFavorite = null;
            //bool? isTrashed = null;
            //string? key = null;
            //AssetOrder? order = null;
            //Guid? personId = null;
            //Guid? userId = null;
            //bool? withPartners = null;
            //bool? withStacked = null;
            //var response = instance.GetTimeBucket(size, timeBucket, albumId, isArchived, isFavorite, isTrashed, key, order, personId, userId, withPartners, withStacked);
            //Assert.IsType<List<AssetResponseDto>>(response);
        }

        /// <summary>
        /// Test GetTimeBuckets
        /// </summary>
        [Fact]
        public void GetTimeBucketsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TimeBucketSize size = null;
            //Guid? albumId = null;
            //bool? isArchived = null;
            //bool? isFavorite = null;
            //bool? isTrashed = null;
            //string? key = null;
            //AssetOrder? order = null;
            //Guid? personId = null;
            //Guid? userId = null;
            //bool? withPartners = null;
            //bool? withStacked = null;
            //var response = instance.GetTimeBuckets(size, albumId, isArchived, isFavorite, isTrashed, key, order, personId, userId, withPartners, withStacked);
            //Assert.IsType<List<TimeBucketResponseDto>>(response);
        }
    }
}
