/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ImmichApi.Client;
using ImmichApi.Api;
// uncomment below to import models
//using ImmichApi.Model;

namespace ImmichApi.Test.Api
{
    /// <summary>
    ///  Class for testing TrashApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TrashApiTests : IDisposable
    {
        private TrashApi instance;

        public TrashApiTests()
        {
            instance = new TrashApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrashApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TrashApi
            //Assert.IsType<TrashApi>(instance);
        }

        /// <summary>
        /// Test EmptyTrash
        /// </summary>
        [Fact]
        public void EmptyTrashTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.EmptyTrash();
        }

        /// <summary>
        /// Test RestoreAssets
        /// </summary>
        [Fact]
        public void RestoreAssetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BulkIdsDto bulkIdsDto = null;
            //instance.RestoreAssets(bulkIdsDto);
        }

        /// <summary>
        /// Test RestoreTrash
        /// </summary>
        [Fact]
        public void RestoreTrashTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.RestoreTrash();
        }
    }
}
