/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing AssetBulkUpdateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetBulkUpdateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetBulkUpdateDto
        //private AssetBulkUpdateDto instance;

        public AssetBulkUpdateDtoTests()
        {
            // TODO uncomment below to create an instance of AssetBulkUpdateDto
            //instance = new AssetBulkUpdateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetBulkUpdateDto
        /// </summary>
        [Fact]
        public void AssetBulkUpdateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetBulkUpdateDto
            //Assert.IsType<AssetBulkUpdateDto>(instance);
        }

        /// <summary>
        /// Test the property 'DateTimeOriginal'
        /// </summary>
        [Fact]
        public void DateTimeOriginalTest()
        {
            // TODO unit test for the property 'DateTimeOriginal'
        }

        /// <summary>
        /// Test the property 'DuplicateId'
        /// </summary>
        [Fact]
        public void DuplicateIdTest()
        {
            // TODO unit test for the property 'DuplicateId'
        }

        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Fact]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }

        /// <summary>
        /// Test the property 'IsArchived'
        /// </summary>
        [Fact]
        public void IsArchivedTest()
        {
            // TODO unit test for the property 'IsArchived'
        }

        /// <summary>
        /// Test the property 'IsFavorite'
        /// </summary>
        [Fact]
        public void IsFavoriteTest()
        {
            // TODO unit test for the property 'IsFavorite'
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'RemoveParent'
        /// </summary>
        [Fact]
        public void RemoveParentTest()
        {
            // TODO unit test for the property 'RemoveParent'
        }

        /// <summary>
        /// Test the property 'StackParentId'
        /// </summary>
        [Fact]
        public void StackParentIdTest()
        {
            // TODO unit test for the property 'StackParentId'
        }
    }
}
