/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing FileReportItemDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileReportItemDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileReportItemDto
        //private FileReportItemDto instance;

        public FileReportItemDtoTests()
        {
            // TODO uncomment below to create an instance of FileReportItemDto
            //instance = new FileReportItemDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileReportItemDto
        /// </summary>
        [Fact]
        public void FileReportItemDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileReportItemDto
            //Assert.IsType<FileReportItemDto>(instance);
        }

        /// <summary>
        /// Test the property 'Checksum'
        /// </summary>
        [Fact]
        public void ChecksumTest()
        {
            // TODO unit test for the property 'Checksum'
        }

        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Fact]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }

        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Fact]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }

        /// <summary>
        /// Test the property 'PathType'
        /// </summary>
        [Fact]
        public void PathTypeTest()
        {
            // TODO unit test for the property 'PathType'
        }

        /// <summary>
        /// Test the property 'PathValue'
        /// </summary>
        [Fact]
        public void PathValueTest()
        {
            // TODO unit test for the property 'PathValue'
        }
    }
}
