/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing FileChecksumResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileChecksumResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileChecksumResponseDto
        //private FileChecksumResponseDto instance;

        public FileChecksumResponseDtoTests()
        {
            // TODO uncomment below to create an instance of FileChecksumResponseDto
            //instance = new FileChecksumResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileChecksumResponseDto
        /// </summary>
        [Fact]
        public void FileChecksumResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileChecksumResponseDto
            //Assert.IsType<FileChecksumResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Checksum'
        /// </summary>
        [Fact]
        public void ChecksumTest()
        {
            // TODO unit test for the property 'Checksum'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
    }
}
