/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing FileChecksumDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileChecksumDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileChecksumDto
        //private FileChecksumDto instance;

        public FileChecksumDtoTests()
        {
            // TODO uncomment below to create an instance of FileChecksumDto
            //instance = new FileChecksumDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileChecksumDto
        /// </summary>
        [Fact]
        public void FileChecksumDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileChecksumDto
            //Assert.IsType<FileChecksumDto>(instance);
        }

        /// <summary>
        /// Test the property 'Filenames'
        /// </summary>
        [Fact]
        public void FilenamesTest()
        {
            // TODO unit test for the property 'Filenames'
        }
    }
}
