/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing OAuthConfigDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OAuthConfigDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OAuthConfigDto
        //private OAuthConfigDto instance;

        public OAuthConfigDtoTests()
        {
            // TODO uncomment below to create an instance of OAuthConfigDto
            //instance = new OAuthConfigDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuthConfigDto
        /// </summary>
        [Fact]
        public void OAuthConfigDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OAuthConfigDto
            //Assert.IsType<OAuthConfigDto>(instance);
        }

        /// <summary>
        /// Test the property 'RedirectUri'
        /// </summary>
        [Fact]
        public void RedirectUriTest()
        {
            // TODO unit test for the property 'RedirectUri'
        }
    }
}
