/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing PathEntityType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathEntityTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PathEntityType
        //private PathEntityType instance;

        public PathEntityTypeTests()
        {
            // TODO uncomment below to create an instance of PathEntityType
            //instance = new PathEntityType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PathEntityType
        /// </summary>
        [Fact]
        public void PathEntityTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PathEntityType
            //Assert.IsType<PathEntityType>(instance);
        }
    }
}
