/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing ScanLibraryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScanLibraryDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScanLibraryDto
        //private ScanLibraryDto instance;

        public ScanLibraryDtoTests()
        {
            // TODO uncomment below to create an instance of ScanLibraryDto
            //instance = new ScanLibraryDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScanLibraryDto
        /// </summary>
        [Fact]
        public void ScanLibraryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScanLibraryDto
            //Assert.IsType<ScanLibraryDto>(instance);
        }

        /// <summary>
        /// Test the property 'RefreshAllFiles'
        /// </summary>
        [Fact]
        public void RefreshAllFilesTest()
        {
            // TODO unit test for the property 'RefreshAllFiles'
        }

        /// <summary>
        /// Test the property 'RefreshModifiedFiles'
        /// </summary>
        [Fact]
        public void RefreshModifiedFilesTest()
        {
            // TODO unit test for the property 'RefreshModifiedFiles'
        }
    }
}
