/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing ServerConfigDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServerConfigDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServerConfigDto
        //private ServerConfigDto instance;

        public ServerConfigDtoTests()
        {
            // TODO uncomment below to create an instance of ServerConfigDto
            //instance = new ServerConfigDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerConfigDto
        /// </summary>
        [Fact]
        public void ServerConfigDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServerConfigDto
            //Assert.IsType<ServerConfigDto>(instance);
        }

        /// <summary>
        /// Test the property 'ExternalDomain'
        /// </summary>
        [Fact]
        public void ExternalDomainTest()
        {
            // TODO unit test for the property 'ExternalDomain'
        }

        /// <summary>
        /// Test the property 'IsInitialized'
        /// </summary>
        [Fact]
        public void IsInitializedTest()
        {
            // TODO unit test for the property 'IsInitialized'
        }

        /// <summary>
        /// Test the property 'IsOnboarded'
        /// </summary>
        [Fact]
        public void IsOnboardedTest()
        {
            // TODO unit test for the property 'IsOnboarded'
        }

        /// <summary>
        /// Test the property 'LoginPageMessage'
        /// </summary>
        [Fact]
        public void LoginPageMessageTest()
        {
            // TODO unit test for the property 'LoginPageMessage'
        }

        /// <summary>
        /// Test the property 'OauthButtonText'
        /// </summary>
        [Fact]
        public void OauthButtonTextTest()
        {
            // TODO unit test for the property 'OauthButtonText'
        }

        /// <summary>
        /// Test the property 'TrashDays'
        /// </summary>
        [Fact]
        public void TrashDaysTest()
        {
            // TODO unit test for the property 'TrashDays'
        }

        /// <summary>
        /// Test the property 'UserDeleteDelay'
        /// </summary>
        [Fact]
        public void UserDeleteDelayTest()
        {
            // TODO unit test for the property 'UserDeleteDelay'
        }
    }
}
