/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing TimeBucketSize
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimeBucketSizeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimeBucketSize
        //private TimeBucketSize instance;

        public TimeBucketSizeTests()
        {
            // TODO uncomment below to create an instance of TimeBucketSize
            //instance = new TimeBucketSize();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimeBucketSize
        /// </summary>
        [Fact]
        public void TimeBucketSizeInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimeBucketSize
            //Assert.IsType<TimeBucketSize>(instance);
        }
    }
}
