/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.110.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ImmichApi.Model;
using ImmichApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ImmichApi.Test.Model
{
    /// <summary>
    ///  Class for testing UserAdminUpdateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserAdminUpdateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserAdminUpdateDto
        //private UserAdminUpdateDto instance;

        public UserAdminUpdateDtoTests()
        {
            // TODO uncomment below to create an instance of UserAdminUpdateDto
            //instance = new UserAdminUpdateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserAdminUpdateDto
        /// </summary>
        [Fact]
        public void UserAdminUpdateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserAdminUpdateDto
            //Assert.IsType<UserAdminUpdateDto>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'QuotaSizeInBytes'
        /// </summary>
        [Fact]
        public void QuotaSizeInBytesTest()
        {
            // TODO unit test for the property 'QuotaSizeInBytes'
        }

        /// <summary>
        /// Test the property 'ShouldChangePassword'
        /// </summary>
        [Fact]
        public void ShouldChangePasswordTest()
        {
            // TODO unit test for the property 'ShouldChangePassword'
        }

        /// <summary>
        /// Test the property 'StorageLabel'
        /// </summary>
        [Fact]
        public void StorageLabelTest()
        {
            // TODO unit test for the property 'StorageLabel'
        }
    }
}
